apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapi
  template:
    metadata:
      labels:
        app: testapi
    spec:
      containers:
        - name: testapi
          image: 599355715474.dkr.ecr.us-east-1.amazonaws.com/demo-api:v1
          ports:
            - containerPort: 9091
          env:
            - name: DATABASE_URL
              value: your-db-connection-url
            - name: PORT
              value: "9091"
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
      imagePullSecrets:
        - name: your-registry-secret-name
---
apiVersion: v1
kind: Service
metadata:
  name: testapi
spec:
  selector:
    app: testapi
  ports:
    - name: http
      port: 9091
      targetPort: 9091
  # type: LoadBalancer

---
kind: Ingress
metadata:
  name: testapi
  # namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: a1123684039b04b808be426dac966ae3-1216601411.ap-south-1.elb.amazonaws.com # ELB DNS
      http:
        paths:
          - pathType: Prefix
            path: /goengine
            backend:
              service:
                name: testapi
                port:
                  number: 9091
