apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql-api
  template:
    metadata:
      labels:
        app: graphql-api
    spec:
      containers:
        - name: graphql-api
          image: 599355715474.dkr.ecr.us-east-1.amazonaws.com/demo-api:v1
          ports:
            - containerPort: 9091
          env:
            - name: DATABASE_URL
              value: your-db-connection-url
            - name: PORT
              value: "9091"
      imagePullSecrets:
        - name: your-registry-secret-name
---
apiVersion: v1
kind: Service
metadata:
  name: graphql-api-service
spec:
  selector:
    app: graphql-api
  ports:
    - name: http
      port: 9091
      targetPort: 9091
  type: LoadBalancer

